fb_login_app/fb_login_app/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('userauth:profile'))),
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('auth/', include('userauth.urls', namespace='userauth')),
]

fb_login_app/userauth/urls.py
from django.conf import settings
from django.urls import path
from . import views

app_name = 'userauth'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('facebook/deauth/', views.FacebookDeauthView.as_view(), name='deauth'),
]

fb_login_app/userauth/models.py
from django.db import models

# Create your models here.

fb_login_app/userauth/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView, RedirectView, View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from social_django.models import UserSocialAuth
from social_core.backends.facebook import FacebookOAuth2
from .utils import load_signed_request


class LoginView(TemplateView):
    """Display login form to user"""
    template_name = "userauth/login.html"

class LogoutView(RedirectView):
    """Process logout"""
    url = '/'
    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

@method_decorator(login_required, name='get')
class ProfileView(TemplateView):
    """Display the user profile"""
    template_name = 'userauth/profile.html'

    def get(self, *args, **kwargs):
        # Add facebook user id and avatar to user object
        params = {'user': self.request.user, 'provider': 'facebook'}
        fb_profile = get_object_or_404(UserSocialAuth, **params)
        self.request.user.facebook_uid = fb_profile.uid
        fb_avatar = 'https://graph.facebook.com/{}/picture?type=large'.format(fb_profile.uid)
        self.request.user.facebook_avatar = fb_avatar
        return super(ProfileView, self).get(*args, **kwargs)


@method_decorator(csrf_exempt, name='dispatch')
class FacebookDeauthView(View):
    """Handle the facebook deauthorization callback"""

    def post(get, request, *args, **kwargs):
        signed_request = request.POST.get('signed_request')
        if not signed_request:
            return HttpResponse('No signed request present', status=400)

        # Handle signed request with social_core
        FacebookOAuth2.load_signed_request = load_signed_request
        fb = FacebookOAuth2()
        parsed_signed_request = fb.load_signed_request(signed_request)

        try:
            params = {'uid': parsed_signed_request.get('user_id'),
                      'provider': 'facebook'}
            social_user = get_object_or_404(UserSocialAuth, **params)
            user = social_user.user
            # Deauth request is successful
            user.is_active = False
            user.save()
            return HttpResponse('Deauthorization successful', status=200)
        except:
            # Deauth request fails
            return HttpResponse('Error deauthorizing application', status=400)

fb_login_app/userauth/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>

{% block html %}
<html lang="en">
{% block head %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block title %}{% endblock %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css" />
    {% block extra_css %}{% endblock %}
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/js/all.min.js"></script>
</head>
{% endblock %}

{% block body %}

<body>

    {% block content %}

    {% endblock %}

    {% block extra_js %}{% endblock %}
</body>
{% endblock %}

</html>
{% endblock %}

fb_login_app/userauth/templates/userauth/login.html
{% extends 'base.html' %}

{% block content %}
<style>
    .button.is-fb-button {
        background-color: #3C5A99;
        color: #FFF;
    }
</style>
<div class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered is-vcentered is-desktop is-mobile">
                <div
                    class="column is-three-quarters-mobile is-two-thirds-tablet is-one-half-desktop is-one-third-widescreen">
                    <div class="card is-rounded">
                        <header class="card-header">
                            <p class="card-header-title">
                                Log in to continue
                            </p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>
                                    This is a simple Django app to implement user login with Facebook.
                                </p>

                                <p class="control has-text-right">
                                    <a class="button is-fb-button" onclick="this.classList.add('is-loading')"
                                    href="{% url 'social:begin' 'facebook' %}">
                                        <span class="icon">
                                            <i class="fab fa-lg fa-facebook-square"></i>
                                        </span>
                                        <span>
                                            Continue with Facebook
                                        </span>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

fb_login_app/userauth/templates/userauth/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered is-vcentered is-desktop is-mobile">
                <div class="column is-three-quarters-mobile is-two-thirds-tablet is-one-half-desktop is-one-third-widescreen">
                    <div class="card is-rounded">
                        <div class="card-content">
                            <div class="media">
                                <div class="media-left">
                                    <figure class="image is-64x64">
                                        <img src="{{ user.facebook_avatar }}" alt="{{ user.get_full_name }}" />
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <p class="title is-4">
                                        {{ user.get_full_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <a href="{% url 'userauth:logout' %}" class="card-footer-item">Logout</a>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}